steps:
# --- 1️⃣ Backend build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:$SHORT_SHA'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:latest'
    - './backend'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:latest'

# --- 2️⃣ Deploy backend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy ats-backend \
        --image asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:latest \
        --platform managed \
        --region asia-south1 \
        --allow-unauthenticated \
        --memory 1Gi \
        --set-env-vars DJANGO_SETTINGS_MODULE=core.settings_production,SECRET_KEY=ats-logiscareers-secret-key-2025-prod,DEBUG=False,ALLOWED_HOSTS=*,CORS_ALLOW_ALL_ORIGINS=True

# --- 3️⃣ Frontend build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Get backend URL dynamically
      BACKEND_URL=$(gcloud run services describe ats-backend --region asia-south1 --platform managed --format 'value(status.url)')/api
      echo "VITE_API_URL=$BACKEND_URL" > ./frontend/.env

      # Build frontend image
      docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:$SHORT_SHA -t asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:latest ./frontend
      docker push asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:$SHORT_SHA
      docker push asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:latest

# --- 4️⃣ Deploy frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy ats-frontend \
        --image asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:latest \
        --platform managed \
        --region asia-south1 \
        --allow-unauthenticated

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:$SHORT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/backend:latest'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:$SHORT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/frontend:latest'

timeout: '1800s'
