steps:
# ---------------- BACKEND ----------------
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend
    - -f
    - backend/Dockerfile
    - backend

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ats-backend
    - --image
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend
    - --region
    - asia-south1
    - --allow-unauthenticated
    - --set-env-vars
    - DJANGO_SETTINGS_MODULE=core.settings_production,DEBUG=False

# ---------------- FRONTEND ----------------
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend
    - -f
    - frontend/Dockerfile
    - frontend

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ats-frontend
    - --image
    - asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend
    - --region
    - asia-south1
    - --allow-unauthenticated
