# Cloud Build config for ATS LogisCareers
# Builds & deploys backend and frontend to Cloud Run

steps:
# ---------------- BACKEND ----------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend:latest'
    - '-f'
    - 'backend/Dockerfile'
    - 'backend'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ats-backend
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend:latest'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--set-env-vars'
    - 'DJANGO_SETTINGS_MODULE=core.settings_production,DEBUG=False,ALLOWED_HOSTS=*,CORS_ALLOW_ALL_ORIGINS=True'

# ---------------- FRONTEND ----------------
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend:latest'
    - '-f'
    - 'frontend/Dockerfile'
    - 'frontend'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend:latest'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ats-frontend
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend:latest'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

# ---------------- Images ----------------
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-backend:latest'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ats/ats-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
